// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBclzqk3wkE7VOywItTnvqgqMOgUrj9OLA',
    appId: '1:688802619926:web:c48aa2e127e03ebb168b37',
    messagingSenderId: '688802619926',
    projectId: 'minimals-51c79',
    authDomain: 'minimals-51c79.firebaseapp.com',
    storageBucket: 'minimals-51c79.appspot.com',
    measurementId: 'G-V4YEW737VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRjzLiXSTxDDX48FWhw-s3sY6fslTRZB8',
    appId: '1:688802619926:android:07c8b479d317e235168b37',
    messagingSenderId: '688802619926',
    projectId: 'minimals-51c79',
    storageBucket: 'minimals-51c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCY323ph2awXUWIAtKn5KvApImfpmy_Y',
    appId: '1:688802619926:ios:18e4ad97245eb6f9168b37',
    messagingSenderId: '688802619926',
    projectId: 'minimals-51c79',
    storageBucket: 'minimals-51c79.appspot.com',
    iosBundleId: 'com.nuyhead.minimals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCY323ph2awXUWIAtKn5KvApImfpmy_Y',
    appId: '1:688802619926:ios:106d22880e1141f1168b37',
    messagingSenderId: '688802619926',
    projectId: 'minimals-51c79',
    storageBucket: 'minimals-51c79.appspot.com',
    iosBundleId: 'com.nuyhead.minimals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBclzqk3wkE7VOywItTnvqgqMOgUrj9OLA',
    appId: '1:688802619926:web:f79c5936c0323020168b37',
    messagingSenderId: '688802619926',
    projectId: 'minimals-51c79',
    authDomain: 'minimals-51c79.firebaseapp.com',
    storageBucket: 'minimals-51c79.appspot.com',
    measurementId: 'G-5M529JVF4Q',
  );
}
